### PR TITLE
Make rake dependency less strict

### PR DESCRIPTION
**Pull request by markburns**

### CODE REVIEW

**Comment by markburns** [comment]
Not sure about the failure. It passes locally.

**Comment by zeisler** [comment]
If you run the rake command you should get some additional Gemfile.lock files for the test rails app. That may fix the broken spec issue.

**Comment by markburns** [comment]
Great, thanks! Passing now, and added `desc` to the rake tasks to make them easier to find with `rake -T`.

**Comment by markburns** [comment]
Fixes #52

**Pull request merged**
